"""More national-portion questions: financing through practice."""

from qutil import item, src

FHA = src("Fair Housing Act, 42 U.S.C. § 3604", "https://www.law.cornell.edu/uscode/text/42/3604")
LEAD = src("Residential Lead-Based Paint Hazard Reduction Act, 42 U.S.C. § 4852d", "https://www.law.cornell.edu/uscode/text/42/4852d")
RESPA = src("Real Estate Settlement Procedures Act § 8, 12 U.S.C. § 2607", "https://www.law.cornell.edu/uscode/text/12/2607")
ECOA = src("Equal Credit Opportunity Act, 15 U.S.C. § 1691", "https://www.law.cornell.edu/uscode/text/15/1691")
TILA = src("Regulation Z TRID rules, 12 C.F.R. § 1026.19", "https://www.consumerfinance.gov/rules-policy/regulations/1026/19")
SHERMAN = src("Sherman Act, 15 U.S.C. § 1", "https://www.law.cornell.edu/uscode/text/15/1")
ADA = src("Americans with Disabilities Act, title III", "https://www.ada.gov/topics/title-iii/")
DNC = src("FTC Telemarketing Sales Rule", "https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule")


def more_national():
    q = []
    A = q.append

    fin = [
        ("One discount point equals:",
         "One percent of the loan amount",
         ["One percent of the sale price", "One percent of the commission", "$100, regardless of the loan"],
         "Points are prepaid interest or a fee computed on the loan, not on the price. Two points on a $200,000 loan cost $4,000."),
        ("Loan-to-value ratio compares the loan with:",
         "The value of the property, often the lower of price or appraisal",
         ["The borrower's gross income", "The annual tax bill", "The broker's commission"],
         "LTV = loan ÷ value. Lenders commonly use the lower of the purchase price and the appraised value so the borrower is not financing above market."),
        ("Private mortgage insurance is typically required when:",
         "A conventional loan's loan-to-value is above 80 percent",
         ["Every VA loan", "The borrower pays all cash", "The house is brand new, regardless of down payment"],
         "PMI protects the lender on many conventional loans with less than 20 percent down. FHA uses a mortgage insurance premium, which is a different product. VA loans use a funding fee rather than monthly PMI."),
        ("PITI stands for:",
         "Principal, interest, taxes, and insurance",
         ["Price, inspection, title, and interest", "Points, income, taxes, and insurance", "Principal, inflation, term, and index"],
         "Housing-payment estimates add principal and interest to monthly taxes and insurance. Some estimates also include mortgage insurance or association dues, but the letters PITI mean those four items."),
        ("The promissory note is the borrower's:",
         "Promise to repay the debt",
         ["Deed transferring title to the lender in every state", "Appraisal", "Listing agreement"],
         "The note is the debt instrument. The mortgage or deed of trust is the security instrument that ties the debt to the property."),
        ("A clause that lets the lender call the loan due when the property is sold is:",
         "An alienation, or due-on-sale, clause",
         ["A defeasance clause", "A prepayment penalty only", "An escalation clause in a purchase offer"],
         "Alienation or due-on-sale lets the lender demand payment if the borrower transfers the property. Defeasance relates to the lien ending when the debt is paid. Acceleration can also be triggered by default."),
        ("An amortized loan's monthly payment is structured so that, over the term:",
         "The loan balance declines as principal is paid",
         ["The payment is interest only and the balance never changes", "The balance grows each month", "Taxes are paid instead of principal"],
         "In a fully amortizing loan, each payment covers interest and some principal, and the balance reaches zero at the end. An interest-only payment does not reduce principal."),
        ("An adjustable-rate mortgage differs from a fixed-rate loan because:",
         "The rate can change with an index, subject to caps in the note",
         ["The rate can never change after the first day", "The federal government guarantees every ARM", "No principal is ever owed"],
         "ARMs start with an initial rate and later adjust based on an index plus a margin, usually with periodic and lifetime caps."),
        ("FHA's role in a typical FHA-insured loan is to:",
         "Insure the lender against loss",
         ["Lend the money from a local FHA bank branch in every town", "Guarantee the loan the way VA does", "Set the salesperson's commission"],
         "FHA insurance protects the lender. The money usually comes from an approved lender. VA guarantees part of the loan for eligible veterans. USDA has its own rural programs."),
        ("A VA loan is best described as:",
         "A loan a lender makes, which VA may guarantee for an eligible veteran",
         ["A grant that never has to be repaid", "Insurance from FHA", "Owner financing with no lender"],
         "VA does not usually lend the purchase money itself. It guarantees a portion of a loan made by a lender to an eligible borrower."),
        ("Owner financing in which the seller keeps title until the buyer pays an agreed amount is often called:",
         "A land contract or contract for deed",
         ["A quitclaim deed delivered on day one with no balance due", "A reverse mortgage", "A conventional 30-year loan"],
         "Under a contract for deed, the buyer takes possession and pays over time, and the seller delivers the deed when the contract is satisfied. The buyer has equitable interest and should still be careful about the seller's existing loans."),
        ("A bridge loan is commonly used to:",
         "Carry a buyer for a short time between the sale of one home and the purchase of another",
         ["Insure a title forever", "Replace property taxes", "Create a life estate"],
         "Bridge, or swing, financing is short-term. It is not a long-term amortizing first mortgage and it is not title insurance."),
        ("A reverse mortgage is aimed at:",
         "Older homeowners who borrow against equity and generally do not make monthly principal payments",
         ["First-time buyers with no down payment required by law in every case", "Builders only", "Tenants paying security deposits"],
         "Reverse mortgages convert home equity into payments to the borrower. They are a distinct product on the financing outline, with age and occupancy rules set by the program."),
        ("RESPA's kickback ban means a licensee must not:",
         "Give or accept a thing of value for referring settlement-service business in a covered loan",
         ["Tell a buyer the names of three lenders", "Charge a commission the seller agreed to in writing", "Recommend a home inspection"],
         "Section 8 of RESPA prohibits kickbacks and unearned fees for referrals of settlement services in federally related mortgage loans. Sharing a brochure is not the same as paying for a referral.",
         RESPA),
        ("Under the TRID rules, a Loan Estimate is generally due:",
         "Within three business days after the lender receives an application",
         ["Three days after closing", "Only if the borrower asks in the second month", "At the listing appointment"],
         "Regulation Z requires the Loan Estimate within three business days of application, and the Closing Disclosure at least three business days before consummation. Those clocks are a favorite exam point.",
         TILA),
        ("The Closing Disclosure must generally be received by the borrower:",
         "At least three business days before consummation",
         ["Any time on the day of closing is always enough", "Within three days after the first payment", "Only by the seller's agent"],
         "The three-business-day waiting period gives the borrower time to review the Closing Disclosure. Last-minute changes to certain terms can restart the wait.",
         TILA),
        ("ECOA prohibits a lender from discriminating in credit because of:",
         "Race, color, religion, national origin, sex, marital status, age, or the fact that income comes from public assistance",
         ["A low credit score", "Insufficient income to repay", "A recent bankruptcy, if applied consistently"],
         "ECOA is a credit-opportunity law. A lender may still underwrite risk. It may not deny credit because income is from public assistance, or because of the listed personal characteristics.",
         ECOA),
        ("A borrower's housing-expense ratio and debt-to-income ratio are used in:",
         "Underwriting, to test whether income can carry the payment and other debts",
         ["Computing the conveyance tax", "Choosing a legal description", "Setting a cap rate"],
         "Underwriters compare PITI, and PITI plus other debts, with gross income. The exam expects you to know what the ratios measure. Program limits change, so a problem will give you the ratio to use."),
        ("Risky features the outline flags include:",
         "Prepayment penalties and balloon payments",
         ["A fixed rate with no balloon", "Escrowing taxes", "A recorded satisfaction of mortgage"],
         "A balloon leaves a large balance due at the end. A prepayment penalty charges the borrower for paying early. Both can surprise a borrower and show up in financing questions."),
        ("Truth in Lending's advertising rules require that if an ad states a specific triggering term, such as the payment amount, the ad must also:",
         "Disclose the other required loan terms, not a teaser alone",
         ["Omit the annual percentage rate", "State only the broker's nickname", "Promise that the rate can never change"],
         "Regulation Z stops ads from dangling a payment or rate without the related disclosures. The APR is the cost-of-credit measure those rules revolve around."),
        ("A home-equity line of credit is:",
         "A revolving credit line secured by the home",
         ["The same instrument as a quitclaim deed", "Unsecured in every case", "A type of listing agreement"],
         "A HELOC lets the owner borrow, repay, and borrow again, up to a limit, with the home as security. It is not purchase-money financing by itself, though it can be used at a purchase."),
        ("A construction loan is typically:",
         "Short-term financing that funds a build, often followed by permanent financing",
         ["A 30-year fixed loan with no draws", "Title insurance", "A security deposit"],
         "Construction loans are advanced in draws as work is inspected. Many borrowers then replace them with a permanent, or take-out, loan."),
        ("Equal monthly payments of principal and interest, with the interest portion largest at the start, describe:",
         "A fully amortizing fixed-rate loan",
         ["An interest-only loan for the entire term", "A reverse mortgage", "A land contract with no payments"],
         "Early payments are mostly interest because the balance is highest then. Later payments retire more principal. The payment amount stays level in a standard fixed amortizing loan."),
        ("If a buyer assumes a loan that has a due-on-sale clause, the lender may:",
         "Demand full payment unless the lender agrees to the assumption",
         ["Be forced to accept the buyer with no review", "Lose the lien automatically", "Convert the loan to a gift"],
         "A due-on-sale clause is why many loans cannot be assumed just because the parties wish it. The lender can call the loan or approve the new borrower."),
    ]
    for row in fin:
        if len(row) == 5:
            stem, correct, wrongs, explanation, source = row
        else:
            stem, correct, wrongs, explanation = row
            source = None
        A(item("financing", stem, correct, wrongs, explanation, source=source, event=("kickback" in stem or "Closing Disclosure" in stem)))

    contracts = [
        ("A valid contract generally requires:",
         "Competent parties, offer and acceptance, consideration, and a legal purpose",
         ["A notarized deed only", "An earnest-money check in every case", "A witness who is the licensee"],
         "Earnest money is common, but the promise to buy and the promise to sell can be the consideration. Without capacity, mutual assent, consideration, and legality, there is no enforceable contract."),
        ("The statute of frauds generally requires contracts for the sale of real estate to be:",
         "In writing to be enforceable",
         ["Spoken in front of two neighbors", "Recorded before they are signed", "Approved by the lender first"],
         "An oral agreement to sell land is usually unenforceable. There are narrow exceptions, but the exam expects the writing rule."),
        ("A contract signed by a person who has been adjudicated incompetent is:",
         "Void",
         ["Voidable only by the other party", "Valid if the price is fair", "An executory option"],
         "A void contract has no legal effect. A voidable contract, such as one signed by a minor in many cases, can be affirmed or rejected by the protected party."),
        ("A contract that was once valid but cannot be enforced in court because the deadline to sue has passed is:",
         "Unenforceable",
         ["Void from the beginning", "Executed", "A novation"],
         "Unenforceable means a defense, such as the statute of limitations or the statute of frauds, blocks a lawsuit. The parties may still perform."),
        ("A promise for a promise is:",
         "A bilateral contract",
         ["A unilateral contract", "A void deed", "An easement"],
         "Most purchase agreements are bilateral: each side promises. A unilateral contract is accepted by performance, as when a seller promises to pay a fee if a broker produces a buyer, depending on how the listing is written. An option is a classic unilateral contract."),
        ("An option agreement gives the optionee:",
         "The right, but not the duty, to buy during the option period",
         ["The duty to buy on the last day", "Title today", "A mortgage"],
         "The optionor is bound to sell if the option is exercised. The optionee does not have to exercise it. Consideration keeps the option open."),
        ("A seller accepts an offer but changes the closing date. That response is:",
         "A counteroffer, which rejects the original offer",
         ["A full acceptance", "A novation that keeps the original offer alive", "An escrow instruction only"],
         "The mirror-image rule means a changed acceptance is a counteroffer. The first offer is dead unless the original offeror accepts the counter."),
        ("Two offers arrive the same afternoon. The listing side should:",
         "Present them as the agency agreement and the law require, without burying one",
         ["Present only the offer that pays the larger commission", "Wait a week to see who calls again", "Accept both so both buyers are under contract for the same house"],
         "Multiple offers are presented, not shopped for the licensee's convenience. Only one can be accepted for a full sale unless the parties structure backups. The seller decides."),
        ("A financing contingency lets the buyer:",
         "End the contract if the stated financing cannot be obtained, within the contingency's terms",
         ["Skip the purchase price", "Force the seller to lend the money", "Avoid writing a good-faith application"],
         "Contingencies are conditions. If a good-faith effort fails, the buyer can usually terminate and recover the deposit as the contract provides. Ignoring the deadline can waive the protection."),
        ("'Time is of the essence' means:",
         "The dates in the contract are essential, and missing one can be a breach",
         ["Dates are suggestions", "The contract need not be in writing", "The broker may keep the deposit automatically"],
         "Without that clause, a short delay is sometimes still substantial performance. With it, the deadline itself matters. Say so in the contract if the parties mean it."),
        ("If a buyer breaches and the contract allows the seller to keep the deposit as the sole remedy, that deposit is treated as:",
         "Liquidated damages",
         ["A deed", "Punitive damages a court must always add on top", "A security deposit under landlord-tenant law"],
         "Liquidated damages are an amount agreed in advance. They are different from suing for actual damages or asking a court for specific performance."),
        ("Specific performance is a remedy that:",
         "Asks the court to make the parties complete the sale",
         ["Cancels the contract and returns everyone to the start with no further order", "Sets a new commission", "Records a mortgage"],
         "Land is treated as unique, so buyers often seek specific performance rather than money alone. Rescission unwinds the deal."),
        ("Rescission means the parties:",
         "Are returned, as far as possible, to their positions before the contract",
         ["Must close on a new date only", "Assign the contract to a lender", "Add a fixture"],
         "Rescission undoes the contract. Cancellation can end future duties. They are easy to mix up, so read the question for 'back to the start.'"),
        ("An executory contract is one that:",
         "Has been signed but not yet fully performed",
         ["Has been fully performed by both sides", "Is void", "Is only a deed"],
         "Executed, in contract language, means fully performed. Executory means duties remain, which is the usual state of a purchase agreement before closing."),
        ("Assignment of a contract transfers:",
         "The assignor's rights, and sometimes duties, to another person",
         ["Title by deed automatically", "The mortgage without paperwork", "A license only"],
         "Most contracts can be assigned unless they say otherwise or the duty is personal. Novation substitutes a new contract and releases the original party. Assignment alone may leave the assignor liable."),
        ("Novation is:",
         "A new contract that replaces an old one and releases a party",
         ["A counteroffer", "A type of deed", "An encroachment"],
         "Use novation when a new buyer takes over and the seller releases the first buyer. A simple assignment may not release the first buyer."),
        ("Electronic signatures on a real-estate contract are:",
         "Generally valid when the parties agree to transact electronically and the law's consumer protections are met",
         ["Void in every housing sale", "Valid only if also carved into stone", "A substitute for consideration"],
         "Federal and state electronic-transaction laws give electronic signatures effect. Parties should still keep a record. A signature method does not fix a missing contract term."),
        ("Consideration in a purchase agreement can be:",
         "The mutual promises of buyer and seller",
         ["Only cash earnest money", "The licensee's commission", "A verbal hope"],
         "Each side's promise is consideration. Earnest money shows good faith and provides damages or a deposit, but a contract can exist without it."),
        ("A minor signs a contract to buy land. In many cases that contract is:",
         "Voidable by the minor",
         ["Void against the adult only, with the minor bound", "A deed", "Automatically recorded"],
         "Minors lack full capacity, so they can usually disaffirm. The adult party generally cannot use the minor's age as the adult's own escape hatch."),
        ("Duress or fraud in the inducement typically makes a contract:",
         "Voidable by the injured party",
         ["Automatically a warranty deed", "Illegal for the whole neighborhood", "A tenancy at sufferance"],
         "The injured party may affirm or avoid the contract. Fraud as to the nature of the document can sometimes make it void. Either way, it is not a healthy contract."),
        ("An offer may be terminated by:",
         "Revocation by the offeror before acceptance, rejection, counteroffer, expiration, or death of a party",
         ["Only by a court", "Only after the deed is recorded", "A second identical offer"],
         "Until acceptance, the offeror can usually withdraw. A counteroffer kills the original offer. Deadlines should be in the offer so it does not linger."),
        ("Acceptance of an offer is effective, under the mailbox rule often taught for exams, when:",
         "It is properly sent, unless the contract requires actual receipt",
         ["The offeror feels ready", "The deed is recorded", "The loan funds"],
         "Many exam items treat a properly dispatched acceptance as effective on dispatch. Modern contracts often say acceptance must be received by a deadline. Read the form."),
        ("A backup offer should be:",
         "Written so it becomes primary only if the first contract ends, as its terms state",
         ["Accepted in full while the first contract is still alive, for the same house", "Kept oral", "Used to raise the first buyer's price without disclosure"],
         "Two primary contracts for one house are a problem. A backup is expressly secondary. Price shopping a current buyer can also breach agency and contract duties."),
        ("If the property is destroyed before closing and the contract is silent, the risk question is serious because:",
         "The parties need the contract's risk-of-loss clause, and equitable title rules may place risk on the buyer in some states",
         ["The licensee must rebuild the house", "Insurance is illegal before closing", "Destruction never affects a real-estate contract"],
         "Risk of loss is a contract and state-law issue. Good forms say who bears a fire before closing and whether insurance proceeds follow the property. Do not guess it away in a client meeting."),
        ("A rider that adds an inspection clause to a preprinted offer is:",
         "An addendum or contingency that becomes part of the contract when the parties accept it",
         ["A listing agreement", "A note", "A variance"],
         "Addenda add terms. Amendments change a contract that already exists. Both should be in writing and signed."),
        ("The parties sign an amendment extending the closing date. The document that controls the date is:",
         "The signed amendment",
         ["The original date, because amendments are informal", "The advertisement", "The salesperson's calendar"],
         "A signed amendment changes the contract. The latest signed writing on that term wins over the earlier page."),
        ("Breach occurs when a party:",
         "Fails to perform a duty the contract requires, without a legal excuse",
         ["Asks a question at the inspection", "Records the deed on time", "Deposits earnest money as promised"],
         "Missing a time-is-of-the-essence deadline, refusing to close, or failing to apply for the loan in good faith can all be breaches, depending on the clause."),
        ("A contract with an illegal purpose, such as a sale that requires a discriminatory refusal, is:",
         "Void",
         ["Voidable only by the discriminating party", "Enforceable if the price is high", "A CMA"],
         "Courts will not enforce an illegal bargain. Fair-housing violations are not a 'term' a contract can legalize."),
        ("Earnest money disputes, when the contract names an escrow holder, are resolved by:",
         "The contract's instructions and, if the parties disagree, a process such as interpleader or the written release both sides sign",
         ["The salesperson keeping the check", "The louder party", "Automatic forfeiture on day three"],
         "The holder is a stakeholder. Paying the wrong person is conversion. The form should say what happens if the deal dies."),
        ("Which document actually transfers title at closing in a typical sale?",
         "The deed",
         ["The purchase agreement", "The Loan Estimate", "The listing"],
         "The purchase agreement is a contract to convey. Title passes when a valid deed is delivered and accepted, subject to recording for priority against later buyers."),
        ("A purchase agreement is executory until:",
         "The parties have performed, usually by delivering the deed and paying the price",
         ["The first showing", "The CMA is emailed", "The licensee posts the listing"],
         "Signing starts the executory period. Closing is the usual moment the sale contract is executed in the sense of fully performed."),
        ("Competency of parties looks at whether a person:",
         "Understands the nature of the act and is of legal age, or has a valid representative",
         ["Has perfect credit", "Lives in the same town as the property", "Can recite the commission split"],
         "Age and mental capacity matter. A conservator or attorney-in-fact may sign if that person has authority. The licensee should not coach an impaired seller through a signature."),
        ("A unilateral contract is formed when:",
         "The requested act is performed",
         ["A promise is exchanged for a promise", "A deed is recorded in every case", "The offeree stays silent"],
         "Silence is not acceptance. In a unilateral setup, doing the act accepts the offer. Bilateral contracts are promise for promise."),
        ("If a contingency deadline passes and the buyer does nothing, the usual risk is that:",
         "The contingency is waived and the buyer must proceed",
         ["The contract becomes void with no further duty", "The seller must cut the price", "The deed is invalid"],
         "Many forms say the contingency dies, and the contract continues, unless the buyer objects in time. Read the clause. Some forms auto-terminate. The point is that deadlines are not decorative."),
        ("Mutual mistake about the identity of the parcel can make a contract:",
         "Voidable, because there was no real agreement on the subject",
         ["A warranty that the wrong lot is fine", "A mortgage", "An easement by necessity"],
         "If both parties think they are bargaining for different things, assent failed. A court can rescind. A small mistake about value is not the same as a mistake about which lot."),
        ("The licensee's job with a preprinted form is to:",
         "Fill in factual blanks the parties agree to, and send legal questions to a lawyer",
         ["Invent clauses that rewrite state law", "Tell the client the form is a substitute for advice in a dispute", "Leave the price blank and fill it in after closing"],
         "Licensees are not lawyers. Completing a standard form as the parties direct is normal. Drafting custom legal language, or giving legal advice, is the unauthorized practice of law."),
    ]
    for i, (stem, correct, wrongs, explanation) in enumerate(contracts):
        A(item("contracts", stem, correct, wrongs, explanation, event=(i in (6, 8, 17))))

    agency = [
        ("A client is the person to whom the licensee owes fiduciary duties. A customer is:",
         "A person the licensee works with but does not represent",
         ["Always the person who pays the commission", "The same as a client", "The town clerk"],
         "Payment does not by itself decide who is the client. The representation agreement does. Customers are owed honesty and fairness, not loyalty."),
        ("The fiduciary duties often remembered as obedience, loyalty, disclosure, confidentiality, accounting, and reasonable care are owed to:",
         "The client",
         ["Every customer in the same degree as the client", "Only the lender", "The neighbor who toured once"],
         "Those duties run to the principal. Honesty and disclosure of material facts still run to customers and other parties. Loyalty does not mean helping the other side against the client."),
        ("Loyalty means the licensee must:",
         "Put the client's interests ahead of the licensee's own",
         ["Hide material defects if the client asks", "Buy the property without telling the client", "Share the client's bottom line with the other side to be friendly"],
         "Self-dealing and secret profits breach loyalty. Loyalty never excuses fraud or concealment of material facts."),
        ("A licensee who wants to buy the client's listing must:",
         "Disclose that interest and avoid using the client's confidential information against the client",
         ["Stay silent so the price stays low", "Assign the listing to a friend with no disclosure", "Wait until after recording and then reveal the purchase"],
         "Buying from a client is a conflict. Disclosure and informed consent, in writing, are the safe path. The client should understand the licensee is no longer only an advocate."),
        ("Confidentiality requires the licensee to keep secret:",
         "The client's bargaining position, motivation, and other confidential information",
         ["Known structural defects", "Information the law requires to be disclosed", "Facts already in a public recorded plat"],
         "Confidential information stays confidential even after the relationship ends. Material property defects are not confidential. They must be disclosed."),
        ("Accounting, as a fiduciary duty, means:",
         "The licensee must track and report money and property held for the client",
         ["The licensee may pool deposits with personal funds if the math is accurate", "Commissions need not be documented", "The client must do the broker's taxes"],
         "Every dollar of other people's money is accounted for. Commingling and conversion are the failures of this duty."),
        ("Obedience means the licensee follows lawful instructions. It does not mean:",
         "Following an instruction to hide a material defect or to discriminate",
         ["Following a lawful instruction on showing times", "Presenting an offer the client asked to see", "Using the price the client set"],
         "Illegal or unethical instructions are refused. The rest of the client's lawful directions are followed."),
        ("An agency relationship can be created by:",
         "A written agreement, and in some cases by conduct that leads a person to believe they are represented",
         ["Silence alone in every state", "The deed at the end of the deal only", "A newspaper ad with no more contact"],
         "Express agency is the written agreement the state usually requires before negotiating. Implied agency can still arise from conduct, which is a reason to be clear about who is represented."),
        ("A special agent is authorized to:",
         "Handle one specific transaction or task",
         ["Bind the client on any subject forever", "Write wills for the client", "Act as a universal agent"],
         "A real-estate broker is usually a special agent. A general agent handles a range of matters, as a property manager might. A universal agent may do nearly everything, usually under a broad power of attorney."),
        ("A property manager hired to run a building on an ongoing basis is closest to:",
         "A general agent",
         ["A universal agent with no limits", "A customer", "A transaction broker in every state"],
         "Ongoing management authority is broader than a single sale. It is still not unlimited. The management agreement sets the bounds."),
        ("A transaction broker, or facilitator, where that status exists, is:",
         "A licensee who assists without being the fiduciary agent of either side",
         ["Automatically a dual agent", "The buyer's attorney", "A lender"],
         "Non-agency roles still require honesty and care with the paperwork. They are not a free pass to favor one side in secret. Some states do not use this status."),
        ("Dual agency means:",
         "The same brokerage or licensee represents both parties in the same transaction",
         ["Two different companies each represent their own client", "The licensee represents nobody", "The seller represents the buyer"],
         "Dual agency is lawful only with informed consent where the state allows it. The licensee cannot fully advocate for both sides at once, which is why consent and limits on confidential information matter."),
        ("A designated-agency arrangement tries to:",
         "Appoint different licensees in one firm to advocate for each party",
         ["Eliminate the need for any disclosure", "Make the receptionist the client", "Convert the firm into a lender"],
         "Designated agency, where allowed, lets each side have an advocate inside one firm. The firm and the people who supervise both sides may still have dual-agency limits."),
        ("An exclusive-right-to-sell listing means the broker earns a commission if:",
         "The property sells during the listing term, no matter who procures the buyer",
         ["Only the listing broker personally finds the buyer", "The property is withdrawn and never sold", "A neighbor mentions the house and nothing more happens"],
         "Exclusive agency lets the owner sell without a commission if the owner finds the buyer alone. Open listings pay only the broker who procures. Exclusive right to sell is the broadest."),
        ("An open listing pays:",
         "Only the broker who procures a ready, willing, and able buyer, and the owner may list with several brokers",
         ["Every broker who ever showed the house, in full", "The owner, as a salary", "No one, by definition"],
         "Open listings are nonexclusive. The procuring cause earns the fee. They are less common than exclusive listings and can create procuring-cause fights."),
        ("A buyer-representation agreement should state:",
         "The duties, the compensation, the term, and how the broker may be paid",
         ["Only the seller's bottom line", "That the buyer owes no duty to tell the truth", "The appraiser's opinion"],
         "Buyer agreements create the agency, say when it ends, and explain compensation, including whether the buyer pays if the seller does not offer it."),
        ("Agency ends when:",
         "The purpose is completed, the term expires, the parties agree, or the law ends it, such as by death of the client or destruction of the property",
         ["The licensee feels bored", "A customer asks a question", "The first advertisement runs"],
         "Completion and expiration are the clean endings. Death, incapacity, destruction, or bankruptcy can end it by law. Some duties, especially confidentiality and accounting, survive."),
        ("A power of attorney used to sign a deed should be:",
         "A written authority that actually covers that act, from a competent principal",
         ["A verbal request at the closing table", "Assumed because the person is a relative", "A substitute for the buyer's loan approval"],
         "The agent under a power of attorney is an attorney-in-fact. The document must authorize the sale. Licensees do not invent authority that is not written."),
        ("Commingling is:",
         "Mixing client funds with the licensee's own money",
         ["Depositing earnest money in the broker's trust account", "Splitting a commission with the cooperating broker", "Keeping a copy of the contract"],
         "Trust money stays in the trust account. Mixing it with operating or personal funds is commingling. Spending it is conversion, which is worse."),
        ("Conversion is:",
         "Using trust money as if it belonged to the licensee",
         ["Moving a deposit from the salesperson to the broker's trust account", "Changing a list price with the seller's written consent", "Amending a closing date"],
         "Conversion is theft of funds held for others. It is among the fastest ways to lose a license and face criminal charges."),
        ("A licensee owes a customer:",
         "Honesty, fair dealing, and disclosure of material facts",
         ["Loyalty and obedience", "Confidential treatment of the customer's bottom line if the licensee represents the other side", "A duty to follow the customer's illegal instructions"],
         "Customers are not clients. You still may not lie to them or hide defects. You also may not give them your client's secrets."),
        ("The procuring cause of a sale is the broker who:",
         "Started an uninterrupted chain of events that led to the agreement",
         ["Drove past the house", "Printed the most flyers, even if another broker wrote the accepted offer", "Holds the earnest money"],
         "Procuring cause is about who produced the buyer, not who spent the most on ads. Open-listing and commission disputes turn on it."),
        ("A net listing is risky because:",
         "The broker's interest in a higher price can conflict with the client's interest, and some states bar the form",
         ["It always produces the best price for the seller", "It is required by federal law", "It removes all duty to disclose defects"],
         "If the broker keeps everything above a net figure, the temptation is to hide the true value. Many states prohibit net listings. Connecticut's regulation does."),
        ("Reasonable care means the licensee:",
         "Uses the skill a competent licensee would use, including checking facts the licensee can check",
         ["Guarantees the house will rise in value", "Acts as the client's lawyer", "Skips questions that might slow a sale"],
         "Care includes accurate information, timely presentation of offers, and knowing when a question belongs to a lawyer, inspector, or appraiser."),
        ("Disclosure of material facts to a customer is required even when:",
         "The client asks the licensee to stay quiet",
         ["The fact is the client's confidential divorce timing and nothing about the property", "The fact is a rumor with no basis", "The fact is the licensee's home address"],
         "Client instructions stop at the law. A known material defect is disclosed. A client's personal motivation usually is not."),
        ("Subagency, in the older multiple-listing model, meant:",
         "A cooperating broker who represented the seller, not the buyer",
         ["A broker who represented only the buyer", "An unlicensed assistant", "A lender"],
         "Before buyer agency was common, cooperating brokers were often subagents of the seller. Treating a buyer as a client while legally working for the seller was a frequent source of undisclosed dual agency."),
        ("An agency disclosure should be made:",
         "Early, before confidential information is exchanged, as state law requires",
         ["After closing", "Only if someone complains", "In the advertisement's fine print a year later"],
         "The point of early disclosure is that people should know whom you represent before they tell you their secrets. Connecticut requires this by the first personal meeting."),
        ("A licensee who represents the seller and also helps the buyer 'just a little' with offer strategy, without consent, risks:",
         "Undisclosed dual agency",
         ["A higher cap rate", "An easement", "A variance"],
         "Advice that looks like advocacy can create an implied agency. If you already represent the seller, that implied duty to the buyer is an undisclosed dual agency."),
    ]
    for i, (stem, correct, wrongs, explanation) in enumerate(agency):
        A(item("agency", stem, correct, wrongs, explanation, event=(i in (4, 11, 27))))

    disc = [
        ("A material fact is a fact that:",
         "A reasonable buyer would consider important in deciding whether to buy, or at what price",
         ["The seller finds embarrassing but that does not affect the property", "Appears only in a novel", "The licensee would rather not discuss"],
         "Material facts affect the decision. A cracked foundation is material. A seller's dislike of the paint color may not be."),
        ("Latent defects are:",
         "Hidden problems a buyer might not see in an ordinary look",
         ["Defects the seller painted over that everyone can see from the sidewalk", "Open permits posted on the door", "The list price"],
         "Latent means hidden. Known latent defects are exactly the facts licensees get in trouble for concealing. Patent defects are obvious."),
        ("A licensee who knows the basement floods and says 'dry as a bone' has:",
         "Misrepresented a material fact",
         ["Used permissible puffing", "Performed a CMA", "Created an easement"],
         "Puffing is vague opinion, such as 'charming street.' A false statement about flooding is fraud or misrepresentation, not sales talk."),
        ("Federal lead-based paint disclosure applies to most housing built before:",
         "1978",
         ["1995", "2010", "1960 only if the buyer has a child"],
         "Congress chose 1978, when residential lead paint was banned. Sellers and landlords of most pre-1978 housing must disclose known lead information and give the required pamphlet.",
         LEAD),
        ("Under the federal lead law, a buyer of pre-1978 housing must be given:",
         "A 10-day period to conduct a lead inspection or risk assessment, unless the parties agree otherwise",
         ["A deed that guarantees no lead is present", "A waiver the seller can sign alone", "Nothing, if the licensee is in a hurry"],
         "The statute gives the purchaser 10 days, unless they mutually agree on a different period. The buyer may waive the inspection, but the waiver has to be the buyer's.",
         LEAD),
        ("Which environmental issue is a classic disclosure and inspection topic?",
         "Underground storage tanks",
         ["The seller's favorite sports team", "The buyer's hobby", "The commission rate"],
         "Tanks, radon, asbestos, lead, mold, and contaminated soil can affect health and value. They belong in the disclosure conversation, not in small talk only."),
        ("A seller's property condition form is best understood as:",
         "The seller's statement of known condition, not a warranty and not a substitute for inspection",
         ["A guarantee the house is perfect", "An appraisal", "A loan commitment"],
         "Condition forms pass on knowledge. They do not replace an inspector, and they do not usually create a new warranty. Buyers who waive inspections take on more risk."),
        ("If a licensee sees a stain, a sagging beam, or a strong mildew smell, the careful step is to:",
         "Disclose the red flag and suggest the buyer have it inspected",
         ["Say nothing unless the seller agrees", "Paint over it before the open house", "Guarantee the cause"],
         "You do not have to be the engineer. You do have to pass on what you actually see and not talk a buyer out of a reasonable inspection."),
        ("Stigmatized-property rules differ by state. A safe national approach is:",
         "Disclose physical and legal conditions the law treats as material, and follow the state's rule on deaths or reputational facts",
         ["Always advertise every death in the headline", "Never disclose a collapsing foundation", "Ask the neighbors to gossip on camera"],
         "Physical defects travel with you in every state. Whether a death or a felony must be volunteered is state-specific. Connecticut defines some of those facts as nonmaterial unless the buyer asks in writing."),
        ("Fair housing advertising should describe:",
         "The property, not the kind of people the seller hopes will live there",
         ["A preferred religion", "A preferred race", "That families with children are unwelcome in an ordinary rental"],
         "Describe the house, the price, and the features. Words that state a preference about a protected class are illegal advertising, with narrow exceptions such as housing for older persons that actually qualifies."),
        ("A proposed use that would need a zoning change should be:",
         "Identified before the buyer is bound, so the contract can address the approval",
         ["Ignored until after closing", "Guaranteed by the licensee", "Treated as a title defect only"],
         "Use and zoning are disclosure and contract issues. A contingency for permits keeps the buyer from being forced to buy a property that cannot be used as planned."),
        ("Radon is:",
         "A colorless gas that can enter buildings from the soil and is commonly tested in home inspections",
         ["A type of mortgage", "A form of joint tenancy", "A deed restriction"],
         "Radon is an environmental disclosure topic. Testing is routine in many markets. The licensee does not invent a reading; the licensee does not hide a known test."),
        ("Asbestos is most concerning when:",
         "It is friable or will be disturbed by renovation",
         ["It is known and left undisturbed, and someone pretends that means it was never present", "It is used as a financing term", "It is a type of easement"],
         "Intact, undisturbed asbestos is often managed in place. Sanding or demolition can release fibers. Known asbestos is a disclosure item, not a decorating tip."),
        ("A seller says a prior owner removed an underground tank but has no closure letter. The licensee should:",
         "Treat the incomplete history as a fact to disclose and a reason for the buyer to investigate",
         ["State in the ad that the tank was certified removed", "Forget it because the yard looks mowed", "Fill the hole and move on"],
         "You report what is known, including the gaps. Inventing a clean closure is misrepresentation."),
        ("Government disclosure requirements on the national outline include:",
         "Lead-based paint disclosure for most pre-1978 housing",
         ["A duty to advertise the seller's medical chart", "A duty to hide flood maps", "A duty to guarantee future value"],
         "Lead disclosure is the federal item the outline names. Flood zones, coastal rules, and local forms may add more. When a map or a seller's knowledge shows a hazard, do not bury it."),
        ("Puffing is:",
         "Exaggerated opinion that a reasonable person would not treat as a hard fact",
         ["A false statement about the roof's age", "A hidden lien", "A loan estimate"],
         "'Best view in town' is puffing if nobody would take it as a measurement. 'New roof in 2024' is a fact, and it must be true."),
        ("A buyer asks whether the roof leaks. The licensee knows it does. The honest answer is:",
         "Yes, and the buyer should inspect it",
         ["'Not that I know of,' to protect the seller", "Silence, then a change of subject", "A promise to pay for a new roof"],
         "Direct questions about known defects get direct answers. Dodging is concealment."),
        ("Surveys are warranted when:",
         "Boundaries, encroachments, or the legal description are in doubt",
         ["The licensee already guessed the lot lines", "The house is a condominium with no land interest of any kind and no question has been raised", "The buyer wants to skip closing"],
         "A survey locates improvements and boundaries on the ground. It is the tool for encroachments and for checking that the fence is actually on the lot. The outline ties surveys to property condition and land use."),
    ]
    for i, row in enumerate(disc):
        if len(row) == 5:
            stem, correct, wrongs, explanation, source = row
        else:
            stem, correct, wrongs, explanation = row
            source = None
        A(item("disclosures", stem, correct, wrongs, explanation, source=source, event=(i in (4, 16))))

    mgmt = [
        ("A property manager's basic client is:",
         "The owner",
         ["The tenant, in the same fiduciary way", "The tax assessor", "The neighboring owner"],
         "The management agreement creates an agency with the owner. Tenants are owed honest dealing and compliance with housing law, not the owner's loyalty."),
        ("A gross lease typically means the tenant pays:",
         "A fixed rent, and the landlord pays the operating expenses",
         ["Rent plus taxes, insurance, and maintenance", "A percentage of gross sales only, with no base rent ever", "Nothing"],
         "Gross: landlord carries the operating costs. Net: tenant pays some or all of them. Percentage: rent is tied to sales, often with a base rent."),
        ("A triple-net lease commonly shifts to the tenant:",
         "Taxes, insurance, and maintenance",
         ["Only the interior paint", "The landlord's income taxes", "The purchase price of the building"],
         "Net, double-net, and triple-net describe how many expense categories the tenant picks up. The exam's plain meaning of triple-net is taxes, insurance, and maintenance."),
        ("A percentage lease is most often used for:",
         "Retail space, with rent tied in part to the tenant's sales",
         ["A week-to-week room in a house only", "Raw land with no tenant", "A life estate"],
         "Retail landlords use percentage rent so the rent reflects the store's success. There is often a base rent plus a percentage above a breakpoint."),
        ("An estate for years is a lease:",
         "For a definite period, with a start and an end",
         ["That renews forever unless a court ends it", "That the tenant may hold after eviction without paying", "That cannot be in writing"],
         "The name is old. The term can be months or years, as long as the end date is certain. No notice is required to end it on that date unless the lease says otherwise."),
        ("A month-to-month tenancy is:",
         "A periodic tenancy that renews each month until proper notice is given",
         ["An estate for years with a fixed end date five years out", "A tenancy at sufferance", "A fee simple"],
         "Periodic tenancies roll on until notice. Tenancy at sufferance is a holdover without permission. Tenancy at will is open-ended and ends at either party's will, as state law allows."),
        ("A tenant who stays after the lease ends, without the landlord's consent, holds:",
         "A tenancy at sufferance",
         ["A new 99-year estate automatically", "A joint tenancy with the landlord", "An easement by necessity"],
         "The landlord may accept rent and create a new periodic tenancy, or treat the occupant as a holdover and pursue possession. The occupant is not a guest and not a fee owner."),
        ("Security deposits in a management account should be:",
         "Kept separate from the manager's operating money and handled as trust funds",
         ["Spent on office rent as long as the manager remembers the amount", "Returned to the owner as a fee on day one", "Converted to cash and stored in a desk"],
         "Other people's money is trust money. State law sets the maximum deposit, the account, interest, and the return deadline. Connecticut's statute is specific."),
        ("Fair housing in property management means the manager must not:",
         "Refuse a qualified applicant because of a protected class, or apply rules unevenly",
         ["Screen for ability to pay the rent", "Enforce a reasonable occupancy limit based on local codes", "Ask for references"],
         "Screening for income, credit, and rental history is lawful when it is consistent. Screening for race, familial status, disability, or another protected class is not. Reasonable accommodations are part of the job."),
        ("The Americans with Disabilities Act, in a property-management setting, is most directly about:",
         "Access to public areas and reasonable changes for people with disabilities",
         ["Setting cap rates", "Choosing a joint tenancy", "The conveyance tax"],
         "Title III covers public accommodations. A rental office open to the public is in that world. Residential units also face fair-housing modification and accommodation rules, which are a related but separate statute.",
         ADA),
        ("Setting rent is primarily a function of:",
         "Market comparison: what similar units actually rent for",
         ["The manager's personal mortgage", "The original construction cost alone", "A number that excludes all vacant units nearby"],
         "A rent schedule looks at competing units, vacancy, condition, and concessions. Charging whatever the owner hopes for, with no market check, produces empty units."),
        ("A ground lease is a lease of:",
         "Land, often long-term, on which the tenant may build",
         ["Only the top floor of a tower for a weekend", "Personal property", "A mortgage"],
         "Ground leases separate ownership of the land from the building the tenant constructs. They are long, and the improvement may revert to the landowner at the end."),
    ]
    for i, row in enumerate(mgmt):
        if len(row) == 5:
            stem, correct, wrongs, explanation, source = row
        else:
            stem, correct, wrongs, explanation = row
            source = None
        A(item("management", stem, correct, wrongs, explanation, source=source))

    title = [
        ("Title passes from seller to buyer when:",
         "A valid deed is delivered and accepted",
         ["The listing is signed", "The buyer views the house", "The appraisal is ordered"],
         "Delivery and acceptance of the deed transfer title. Recording protects that title against later claimants. It is not what makes the deed effective between the parties."),
        ("A general warranty deed promises that the grantor will:",
         "Defend the title against claims arising both before and during the grantor's ownership",
         ["Transfer only whatever interest the grantor has, with no promises", "Guarantee the property's future market value", "Pay the buyer's loan"],
         "General warranty gives the broadest title covenants. Special warranty usually covers only the grantor's own period of ownership. A quitclaim makes no title promises."),
        ("A quitclaim deed:",
         "Conveys whatever interest the grantor has, with no warranties",
         ["Is the strongest warranty deed", "Cannot be recorded", "Creates a mortgage"],
         "Quitclaim deeds are used to clear clouds, release claims, or transfer between people who know each other. They are a weak deed for an arm's-length buyer who wants promises."),
        ("Recording a deed gives:",
         "Constructive notice to the world",
         ["A guarantee that the grantor owned the land", "Title insurance automatically", "A variance"],
         "Constructive notice means later buyers are treated as if they knew what is in the land records. Recording does not cure a forged deed or a deed from someone who never owned the land."),
        ("A chain of title is:",
         "The history of conveyances linking the present owner back to earlier owners",
         ["The list of tenants", "The amortization schedule", "A survey"],
         "Title searches follow the chain. A break, a missing spouse's signature, or an unreleased lien is a cloud."),
        ("Marketable title is title a reasonable buyer would accept because it is:",
         "Free of undisclosed defects that would expose the buyer to litigation or doubt",
         ["Insured, even if a known defect remains", "Perfect in a philosophical sense and free of zoning", "Whatever the seller says it is"],
         "Marketable does not mean there is no easement for a utility. It means there is no serious, unresolved defect. Insurable title is different: a title company may insure over a problem the buyer could still object to as unmarketable."),
        ("Title insurance protects the insured against:",
         "Covered title defects that exist at the policy date and were not excluded",
         ["Future zoning changes", "A drop in market value", "Physical wear of the roof"],
         "The policy is about title as of the date, subject to exceptions. It is not a home warranty and not hazard insurance."),
        ("An owner's title policy is usually paid for at closing and protects:",
         "The owner, for as long as that owner or the owner's heirs have an interest",
         ["Only the lender, and only until the first payment", "The salesperson", "The neighbor"],
         "The lender's policy protects the mortgagee and shrinks as the loan is paid. The owner's policy protects the buyer. Who pays is a contract term, but the roles are different."),
        ("A cloud on title is:",
         "A claim, lien, or break that makes ownership uncertain",
         ["A rain delay at the open house", "A low appraisal", "A counteroffer"],
         "Clouds are removed by releases, corrective deeds, or a quiet-title action. Ignoring a cloud is how closings get postponed."),
        ("Prorations at closing divide:",
         "Items such as taxes, rent, and association dues so each side pays its share of the period",
         ["The commission according to federal law", "The land into government sections", "Personal property that was excluded from the sale"],
         "The closing statement shows credits and debits. The contract should say whether the seller or the buyer owns the day of closing, and whether the year is 360 or 365 days."),
        ("A short sale is a sale in which:",
         "The lender agrees to accept less than the full mortgage balance",
         ["The listing period is under one week", "The buyer pays cash in under an hour", "Title passes without a deed"],
         "The lender is a necessary participant because the sale will not retire the whole debt. Short sales take lender approval and can fail late."),
        ("Foreclosure is:",
         "The legal process a lender uses to enforce a lien after default",
         ["A voluntary gift of the deed with no default", "A type of lease", "An appraisal method"],
         "Judicial foreclosure goes through court. Nonjudicial foreclosure follows a power-of-sale clause where state law allows it. Either way, the lien is being enforced."),
        ("A home warranty is:",
         "A service contract covering certain repairs for a stated term",
         ["The same as an owner's title policy", "A deed covenant", "Hazard insurance on the structure"],
         "Warranties, title insurance, and homeowners insurance solve different problems. The exam expects you to keep them apart."),
        ("Essential elements of a valid deed include:",
         "A competent grantor, a grantee, words of conveyance, a description, and delivery",
         ["The buyer's loan approval", "A comparative market analysis", "Consideration that must be the full market value and nothing less"],
         "Deeds can recite nominal consideration. They still need a granting clause, an identifiable property, and delivery. Recording is strongly wise and often essential for priority, but delivery is what moves title between the parties."),
        ("A special warranty deed limits the grantor's defense of title to:",
         "Defects that arose during the grantor's ownership",
         ["Every defect back to the sovereign", "No defects at all, like a quitclaim", "Physical defects in the roof"],
         "Special, or limited, warranty is narrower than general warranty and broader than quitclaim. Foreclosure and fiduciary deeds are often limited."),
        ("Escrow at closing is used so that:",
         "A neutral holder can follow the parties' instructions and disburse when conditions are met",
         ["The salesperson can spend the deposit", "The deed can be signed in pencil and never delivered", "Taxes can be skipped"],
         "The escrow holder is a stakeholder. Conditions such as loan funding, title, and prorations are satisfied before money and the deed trade places."),
        ("A corrective deed is used to:",
         "Fix an error in an earlier deed, such as a misspelled name or a bad description",
         ["Avoid paying off a mortgage", "Create a new mortgage", "Change zoning"],
         "Corrections should be documented, not whispered. A new deed that says it corrects the earlier one, properly executed and recorded, is the usual cure."),
        ("Probate sales differ because:",
         "The personal representative's authority and the court's oversight can limit how the sale is made",
         ["No deed is required", "The buyer cannot obtain title insurance", "The property is always exempt from disclosure rules that otherwise apply"],
         "The outline flags probate as a special process. The seller is acting in a fiduciary role. Deadlines, notices, and court confirmation may apply. Ask who has authority to sign."),
    ]
    for i, (stem, correct, wrongs, explanation) in enumerate(title):
        A(item("title", stem, correct, wrongs, explanation, event=(i in (9, 10))))

    practice = [
        ("The federal Fair Housing Act's named protected classes include:",
         "Race, color, religion, sex, national origin, familial status, and disability",
         ["Credit score, occupation, and hairstyle only", "Age and marital status, which are the federal list", "Only race and religion"],
         "Those seven are the statute's classes. Age and marital status are not federal fair-housing classes, though a state like Connecticut adds them. Familial status protects households with children under 18.",
         FHA),
        ("Blockbusting is:",
         "Persuading owners to sell by playing on fear that a protected class is moving in",
         ["Refusing a loan because of the neighborhood's racial makeup", "Directing buyers only toward certain neighborhoods", "A lawful listing presentation"],
         "Blockbusting is the panic-selling tactic. Redlining is discriminatory lending or insurance by area. Steering is directing people toward or away from neighborhoods because of a protected class.",
         FHA),
        ("Steering is:",
         "Guiding buyers or renters toward or away from areas because of a protected class",
         ["Adjusting a comparable sale for a garage", "A type of deed", "A lawful request for a first-floor unit by a person who needs it"],
         "Choices belong to the customer. Suggestions based on race, religion, or familial status are steering. Answering a request for features, such as one-floor living, is not.",
         FHA),
        ("Redlining is:",
         "Refusing to lend or insure based on the racial or ethnic character of a neighborhood",
         ["Drawing a boundary on a survey", "A prepayment penalty", "An open listing"],
         "The name comes from lines once drawn on maps. It is illegal whether or not anyone still uses a red pen.",
         FHA),
        ("A housing provider must allow a person with a disability to make reasonable modifications to the unit, typically:",
         "At the tenant's expense, when needed for full enjoyment, with restoration rules the statute allows",
         ["Only if the modification is free to everyone else as well", "Never, if the landlord prefers matching paint", "Only after a variance from the real-estate commission"],
         "Fair housing requires reasonable modifications and reasonable accommodations. A landlord may, when it is reasonable, condition a rental modification on restoring the interior, fair wear excepted.",
         FHA),
        ("Which statement may violate fair-housing advertising rules?",
         "'Perfect for a single professional, no kids'",
         ["'Three bedrooms, near the bus line'", "'Walk-out basement'", "'Updated kitchen'"],
         "Describe the property. 'No kids' discriminates based on familial status unless the housing qualifies as housing for older persons. Marital and family preferences are a common trap."),
        ("An antitrust violation in real estate is:",
         "Brokers agreeing to charge the same commission",
         ["One broker independently choosing a fee", "A seller negotiating a lower fee", "Two brokers cooperating on one sale with their clients' consent"],
         "Price fixing is a Sherman Act problem. Each brokerage sets its own fees. A seller may always try to negotiate. Cooperation on a listing is not the same as a conspiracy to fix prices.",
         SHERMAN),
        ("Dividing a town so each brokerage agrees to stay out of the others' areas is:",
         "Market allocation, an antitrust violation",
         ["A CMA", "A legal multiple-listing rule", "Designated agency"],
         "Allocating territories or customers is a restraint of trade. So is a group boycott of a discount broker.",
         SHERMAN),
        ("The National Do Not Call rules mean a licensee should:",
         "Not call numbers on the registry to solicit, unless an exception such as an existing business relationship applies",
         ["Call anyone, because real estate is exempt from the registry entirely", "Use a spoofed number", "Text people who opted out"],
         "The Telemarketing Sales Rule applies to sales calls. An established business relationship is a limited exception, often up to 18 months after a transaction or 3 months after an inquiry. Company-specific do-not-call requests still control.",
         DNC),
        ("A salesperson's online ad should:",
         "Identify the licensee and the brokerage in the way state rules require, and stay accurate",
         ["Look like a private owner if that gets more clicks", "Hide the brokerage because the page is personal", "Promise that every listed home will appreciate"],
         "Technology does not repeal advertising rules. The firm name, a current price, and no false urgency are the baseline. Connecticut's regulation is specific about names and contact information."),
        ("Commingling client funds is:",
         "A violation of the duty to account and a common ground for discipline",
         ["Required, so the broker earns interest", "Allowed under $500", "The same as issuing a receipt"],
         "Trust money is separated, documented, and disbursed only as instructions allow. A receipt is good. Mixing the money is not."),
        ("An independent-contractor salesperson usually:",
         "Controls work hours and is paid by commission, under a written agreement, while the broker still supervises licensed activity",
         ["Has no broker and needs no license", "Is paid only an hourly wage with taxes withheld in every state by statute", "Cannot be held to advertising rules"],
         "The tax status and the licensing status are different. A 1099 worker can still be supervised for license-law purposes. Connecticut even has a statutory liability rule for independent-contractor salespersons."),
        ("Due diligence in a transaction means:",
         "Taking reasonable steps to verify information and to recommend the right experts",
         ["Closing as fast as possible with no questions", "Guaranteeing the buyer's profit", "Replacing the attorney, inspector, and appraiser"],
         "Due diligence is investigation. Licensees coordinate it. They do not pretend to be every profession on the closing checklist."),
        ("A licensee posts a client's pre-approval letter, with account numbers visible, on social media. That is:",
         "A failure to protect confidential personal information",
         ["Required advertising", "A RESPA-compliant disclosure", "Harmless because the sale has not closed"],
         "Financial information is confidential. Advertising the house is fine. Advertising the buyer's bank balances is not."),
        ("Which question is unlawful in a listing interview?",
         "'Will you be comfortable selling to a family with children?'",
         ["'When would you like to move?'", "'Have you signed another listing?'", "'What repairs have you made?'"],
         "Questions that invite discrimination are the licensee's problem even if the seller brought up a bias. The answer is to decline the instruction and explain the law."),
        ("Housing for older persons can, if it actually qualifies, restrict occupancy by:",
         "Families with children, under the familial-status exemption",
         ["Race", "Religion", "National origin"],
         "The exemption is narrow and specific: certain 62-and-older or 55-and-older communities that meet the statutory tests. It is not a license to discriminate on other bases.",
         FHA),
        ("A brokerage's office, open to the public, must consider the ADA when:",
         "A person with a disability needs a reasonable way to use the office's services",
         ["Setting the commission", "Choosing comps", "Prorating taxes"],
         "Title III reaches public accommodations, including many real-estate offices. The duty is reasonable access, not a rewrite of the building overnight when a lesser step would work.",
         ADA),
        ("Tie-in agreements that force a client to use the broker's related service as a condition of the listing can raise:",
         "An antitrust problem",
         ["A duty to do so under RESPA", "A requirement of a general warranty deed", "No issue if the service is convenient"],
         "Conditioning one product on another can be a tying arrangement. RESPA separately restricts required use of a particular title company in covered loans."),
        ("A truthful statement of a commission that one brokerage charges, with no agreement with competitors, is:",
         "Lawful independent pricing",
         ["Price fixing", "Market allocation", "Redlining"],
         "Antitrust punishes agreements among competitors. A single firm's published fee, which a client may negotiate, is ordinary business."),
        ("When a customer says 'don't show me houses in that neighborhood; I don't want to live near those people,' the licensee should:",
         "Refuse the discriminatory instruction and offer choices based on property features and price",
         ["Follow it, because the customer is not a client", "Write it into the buyer agreement as a special stipulation", "Ask the neighbors to confirm who lives there"],
         "You may not carry out discrimination for a customer or a client. Shift the search to lawful criteria: price, size, schools as published data, commute."),
        ("RESPA applies in spirit and in its settlement rules to:",
         "Federally related mortgage loans, including most loans on one-to-four family homes",
         ["Every all-cash land sale with no lender", "A commercial lease of a factory with no loan", "A gift of a house to a child"],
         "No loan, no RESPA. Most home loans from institutional lenders are covered. The kickback rules are about settlement services in those loans.",
         RESPA),
        ("A broker offers a prize to anyone who refers a buyer, including unlicensed friends, and pays them from commission. The risk is:",
         "Paying an unlicensed person for brokerage activity, which license law commonly forbids",
         ["Nothing, because a prize is not money", "A requirement under antitrust law", "A title defect"],
         "Casual referral fees to unlicensed people are a frequent violation. Some states allow a small gift that is not tied to a successful transaction. Paying for procuring a buyer usually requires a license."),
        ("Teams and assistants may prepare flyers. They may not, unless licensed and allowed:",
         "Negotiate price or terms with a buyer",
         ["Put stamps on envelopes", "Enter data the licensee supplies", "Schedule a showing the licensee approved"],
         "The line is negotiation and licensed activity. Clerical help is fine. Strategy, pricing talks, and escrow authority are not."),
        ("A comparative market analysis shared with a lender as if it were an appraisal is:",
         "A misrepresentation of the licensee's role",
         ["Required by the appraisal standards board for every listing", "The same product as a certified appraisal", "A deed"],
         "Say what the document is. A price opinion is not an appraisal, and it should not be dressed up as one for a loan file."),
        ("Confidential information received in a prior agency:",
         "Stays confidential when the licensee later represents someone else",
         ["May be used freely after the listing expires", "Must be posted to the multiple-listing remarks", "Becomes the new client's property"],
         "The duty survives. A new client is told up front if a conflict means you cannot disclose something you already know."),
        ("Which practice is a lawful response to a disability-related request for an assistance animal in housing, assuming no specific disqualification?",
         "Grant a reasonable accommodation even if the building has a no-pets rule",
         ["Charge a pet deposit because the animal is always a pet", "Deny the request because other tenants prefer no animals", "Require the animal to be a certified breed"],
         "Fair housing treats assistance animals as accommodations, not pets. Extra pet rent or a blanket no-pets rule does not defeat a needed accommodation. The animal can still be required to be under control."),
        ("Do-not-call requests made to your own company should be:",
         "Honored, even if a national exemption might otherwise allow a call",
         ["Ignored after 24 hours", "Sold to other brokerages", "Used as a reason to call more often"],
         "An internal do-not-call request is its own obligation. The registry is not the only list that matters.",
         DNC),
        ("A sign in the window that says 'Christian tenants preferred' is:",
         "Discriminatory advertising",
         ["Protected opinion with no housing consequence", "Required disclosure", "A covenant"],
         "Ads may not state a religious preference. The same is true of race, sex, disability, and familial status, outside narrow statutory exemptions that this sign does not meet.",
         FHA),
    ]
    for i, row in enumerate(practice):
        if len(row) == 5:
            stem, correct, wrongs, explanation, source = row
        else:
            stem, correct, wrongs, explanation = row
            source = None
        A(item("practice", stem, correct, wrongs, explanation, source=source, event=(i in (1, 6, 19))))

    return q
