"""National-portion questions written for the PSI salesperson outline. Not copied from prep books."""

from qutil import item, src

FHA = src("Fair Housing Act, 42 U.S.C. § 3604", "https://www.law.cornell.edu/uscode/text/42/3604")
LEAD = src("Residential Lead-Based Paint Hazard Reduction Act, 42 U.S.C. § 4852d", "https://www.law.cornell.edu/uscode/text/42/4852d")
RESPA = src("Real Estate Settlement Procedures Act, 12 U.S.C. § 2607", "https://www.law.cornell.edu/uscode/text/12/2607")
ECOA = src("Equal Credit Opportunity Act, 15 U.S.C. § 1691", "https://www.law.cornell.edu/uscode/text/15/1691")
TILA = src("Truth in Lending Act / Regulation Z (TRID), 12 C.F.R. § 1026.19", "https://www.consumerfinance.gov/rules-policy/regulations/1026/19")
SHERMAN = src("Sherman Act, 15 U.S.C. § 1", "https://www.law.cornell.edu/uscode/text/15/1")
ADA = src("Americans with Disabilities Act, title III, 42 U.S.C. § 12181", "https://www.law.cornell.edu/uscode/text/42/12181")
DNC = src("FTC Telemarketing Sales Rule", "https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule")
CFPB_RESPA = src("CFPB Regulation X, 12 C.F.R. part 1024", "https://www.consumerfinance.gov/rules-policy/regulations/1024/")


def national_questions():
    q = []
    A = q.append

    # Property ownership
    own = [
        ("A person owns a house alone, with no co-owner. That form of ownership is called:",
         "Ownership in severalty",
         ["Joint tenancy", "Tenancy in common", "A license to use"],
         "Severalty means the estate is severed from everyone else: one owner. Joint tenancy and tenancy in common require more than one owner."),
        ("Two friends buy a duplex. The deed says they may have unequal shares and that a deceased owner's share passes by will, not automatically to the survivor. They most likely hold title as:",
         "Tenants in common",
         ["Joint tenants with right of survivorship", "Owners in severalty", "A tenancy at sufferance"],
         "Tenants in common may hold unequal shares, and there is no right of survivorship. A joint tenancy's signature feature is survivorship."),
        ("Four unities — time, title, interest, and possession — are associated with which ownership form?",
         "Joint tenancy",
         ["Tenancy in common", "An easement in gross", "A month-to-month lease"],
         "Traditional joint tenancy is created when the co-owners take the same interest, at the same time, by the same instrument, with equal rights of possession. Tenancy in common requires only unity of possession."),
        ("A joint tenant sells that tenant's share to a new buyer. As to the remaining original joint tenant and the buyer, the ownership typically becomes:",
         "A tenancy in common",
         ["A stronger joint tenancy", "An estate for years", "A license"],
         "Conveying one joint tenant's interest breaks the unities as to that share. The buyer and the remaining owner hold as tenants in common."),
        ("Grandparent deeds a house to a child for the child's life, and then to a grandchild. The grandchild's future interest is a:",
         "Remainder",
         ["Life estate", "Easement by necessity", "License"],
         "The child has a life estate. The grandchild holds the remainder, which becomes possessory when the life estate ends. A reversion would come back to the original grantor."),
        ("A landowner keeps the right to get the property back when a life estate ends. That future interest is a:",
         "Reversion",
         ["Remainder in a stranger", "Profit à prendre only", "Encroachment"],
         "If the grantor does not give the future interest to someone else, it reverts to the grantor, or the grantor's estate, when the measuring life ends."),
        ("A fence built by the neighbor crosses two feet onto the owner's lot. The fence is an example of:",
         "An encroachment",
         ["An easement appurtenant", "A joint tenancy", "A trade fixture"],
         "An encroachment is a physical intrusion of a structure or object onto another's land. It can cloud title and affect value even when no easement was granted."),
        ("A written right to cross a neighbor's driveway to reach a landlocked back lot, intended to benefit that lot, is typically:",
         "An easement appurtenant",
         ["A license that always transfers with the person only", "A lien", "Personal property"],
         "An easement appurtenant benefits a parcel (the dominant estate) and burdens another (the servient estate). It generally transfers with the land."),
        ("A utility company holds a right to run lines across many parcels, and the right does not benefit a neighboring lot the company owns. That right is typically:",
         "An easement in gross",
         ["A tenancy in common", "A remainder", "A homestead exemption"],
         "An easement in gross benefits a person or entity rather than a neighboring parcel. Utility rights are the classic example."),
        ("Permission to park on a neighbor's field for one weekend, revocable at the neighbor's will, is a:",
         "License",
         ["Easement by prescription", "Fee simple absolute", "Mechanic's lien"],
         "A license is permission, not an interest in land. Unlike an easement, it is generally revocable and does not bind later owners by itself."),
        ("Mineral rights are sold, but the seller keeps the house and yard. Those minerals are an example of:",
         "Rights that can be severed from the surface",
         ["A fixture that lost its identity", "Personal property only if still in the ground", "A leasehold"],
         "Air, mineral, and water rights may be conveyed separately from the surface. The buyer of the minerals holds an interest in real property."),
        ("A freestanding refrigerator in a rented apartment, installed by the tenant and removable without damage, is ordinarily:",
         "Personal property",
         ["A fixture that belongs to the landlord automatically", "Real property because it is indoors", "An encroachment"],
         "Personal property is movable. An item becomes a fixture, and part of the real estate, when it is annexed with the intent that it stay. A freestanding appliance usually remains personal property."),
        ("Which description starts at a monument and follows distances and compass directions around the parcel?",
         "Metes and bounds",
         ["Lot and block only", "A street address by itself", "A rectangular government survey township only"],
         "Metes are distances and bounds are directions or boundaries. Lot and block refers to a recorded plat. A street address is not a legal description."),
        ("A deed describes the land as 'Lot 12, Block 4, of Shoreline Map, recorded in Map Book 9, page 22.' That is:",
         "A lot and block description",
         ["A metes-and-bounds call without a plat", "A government rectangular section", "A personal-property bill of sale"],
         "Lot and block, also called a recorded plat, identifies a parcel by lot and block on a map filed in the land records."),
        ("In the government rectangular survey, a section contains about how many acres?",
         "640",
         ["36", "43,560", "160 only, never more"],
         "A township is about 36 sections. A standard section is about one square mile, or 640 acres. 43,560 is the number of square feet in one acre."),
        ("A town's unpaid property tax is a lien. In general, that lien:",
         "Encumbers the property and can lead to a tax sale if unpaid",
         ["Is only a personal promise with no effect on title", "Erases all mortgages automatically on the due date", "Is an easement in gross"],
         "A property-tax lien attaches to the real estate. It can affect title and value and, if enforced, can result in a tax foreclosure or sale. Priority rules vary, but the lien is real."),
        ("A contractor who supplied labor for a kitchen and was not paid may look to:",
         "A mechanic's lien, if the statutory steps are followed",
         ["An easement by necessity", "A life estate", "Ownership in severalty"],
         "Mechanic's lien statutes let unpaid contractors and suppliers claim a lien against the improved property when they follow the required notices and deadlines."),
        ("A buyer at a closing discovers the seller's cousin has an unreleased mortgage on the property. That mortgage is:",
         "A lien that can prevent marketable title until it is released or paid",
         ["Personal property of the cousin", "A license", "A fixture"],
         "A mortgage is a lien. An unreleased lien is an encumbrance. Buyers and title insurers treat open liens as title problems."),
        ("Which interest is measured by someone's lifetime and then ends?",
         "A life estate",
         ["A fee simple absolute", "An estate for years of five calendar years", "A month-to-month periodic tenancy"],
         "A life estate lasts for the measuring life and then passes as a remainder or reversion. A fee simple can last forever. An estate for years is a lease for a fixed term."),
        ("A cooperative buyer generally receives:",
         "Shares in a corporation and a proprietary lease, rather than a deed to a unit",
         ["A fee-simple deed to the airspace only", "A tenancy at sufferance", "An easement in gross and nothing else"],
         "In a co-op, the corporation owns the real estate. The resident owns stock and the right to occupy under a proprietary lease. A condominium owner, by contrast, holds title to a unit."),
        ("In a condominium, the owner typically holds title to a unit plus:",
         "An undivided interest in the common elements",
         ["Sole ownership of the exterior roof in severalty", "A lease from the town", "No interest in hallways or grounds"],
         "Condominium ownership combines a separate unit interest with a shared interest in common elements such as halls, grounds, and the structure, subject to the declaration and bylaws."),
        ("A time-share purchaser most nearly has:",
         "A right to use, or an interval ownership in, property for recurring periods",
         ["A fee simple in the entire building all year", "A mechanic's lien", "Only a personal license that can never be recorded"],
         "Time-shares divide use or ownership into intervals. The form can be a deeded interest or a right-to-use contract. It is a common-interest arrangement the exam outline treats separately from a full-year fee simple."),
        ("Land is described as the north half of the northeast quarter of a section. About how many acres is that?",
         "80",
         ["20", "160", "320"],
         "A section is about 640 acres. A quarter section is about 160. Half of that quarter is about 80 acres."),
        ("Water rights that go with land touching a river are generally called:",
         "Riparian rights",
         ["Littoral rights, which is the term for ocean or lake frontage only in some texts, but not for a river", "Air rights", "Emblements"],
         "Riparian rights concern land bordering flowing water such as a river or stream. Littoral rights concern land bordering a lake, sea, or similar body. The labels are the ones the exam expects."),
        ("Crops already planted by a tenant, which the tenant has the right to harvest, are called:",
         "Emblements",
         ["Fixtures", "Trade fixtures", "Encroachments"],
         "Emblements are annual crops produced by labor. A tenant who planted them may usually return to harvest them even after the tenancy ends. They are treated as personal property."),
        ("A bookstore tenant bolts custom shelves to the walls. The shelves were installed for the business and can be removed, repairing the wall. They are:",
         "Trade fixtures",
         ["Real property the moment they are bolted", "An easement", "A remainder"],
         "Trade fixtures are personal property of the commercial tenant, installed for business, and removable before the lease ends if the premises are restored."),
        ("Which item is real property?",
         "A built-in dishwasher wired and plumbed into the kitchen",
         ["A framed poster leaning on a shelf", "A freestanding washer with a plug", "Patio furniture"],
         "Annexation, adaptation, and the intent to make the item a permanent part of the building point to a fixture. Built-in, plumbed appliances are usually fixtures. Freestanding items usually are not."),
        ("Adverse possession is a way a person may gain title by possessing land in a way that is open and hostile for the statutory period. It is best classified as:",
         "A potential encumbrance or threat to the record owner's title while the period runs, and a title claim if it ripens",
         ["A license", "A mortgage", "Personal property"],
         "The outline treats adverse possession as a potential encumbrance on title. If the possession meets the state's tests for the required years, the possessor may gain title. Permission from the owner defeats hostility."),
    ]
    for stem, correct, wrongs, explanation in own:
        A(item("ownership", stem, correct, wrongs, explanation))

    # Land use
    land = [
        ("The government's power to take private land for public use, with just compensation, is:",
         "Eminent domain",
         ["Escheat", "A variance", "Police power without compensation"],
         "Eminent domain is the taking power. The court process is condemnation. Police power regulates without a taking. Escheat sends ownerless property to the state."),
        ("Property taxes and special assessments exist because government has the power of:",
         "Taxation",
         ["Escheat", "A license", "Novation"],
         "Taxation is an independent governmental power. A special assessment is a charge for a local improvement, such as a sidewalk, that benefits particular parcels."),
        ("When a person dies with no will and no heirs who can take the land, title may pass to the state by:",
         "Escheat",
         ["Eminent domain", "A variance", "Blockbusting"],
         "Escheat is the fallback when ownership has nowhere else to go. It is not a taking for a highway, and it is not a zoning relief valve."),
        ("A zoning board allows a homeowner to build closer to the lot line than the ordinance permits, because strict enforcement would cause undue hardship. That relief is a:",
         "Variance",
         ["Nonconforming use", "Special assessment", "Deed restriction"],
         "A variance is permission to vary from the zoning rules for a specific parcel, usually after a hardship showing. A nonconforming use is a use that was legal before the rule changed."),
        ("A warehouse legally operated before the area was rezoned residential. It may usually continue as:",
         "A nonconforming use",
         ["A variance that must be reapplied for every week", "An escheat", "A trade fixture"],
         "Nonconforming uses are grandfathered. They can often continue, but expansion or reconstruction after destruction may be limited by the ordinance."),
        ("Deed restrictions and subdivision covenants are examples of:",
         "Private land-use controls",
         ["Eminent domain", "Escheat", "A government rectangular survey"],
         "Private controls come from owners and developers: conditions, covenants, and restrictions. Zoning, building codes, and eminent domain are public controls."),
        ("A subdivision's CC&Rs ban overnight boat parking. Those rules are enforced by:",
         "The owners, often through the association, as private covenants",
         ["The federal reserve", "A title insurance company as a tax collector", "Escheat"],
         "Covenants, conditions, and restrictions run with the land when properly created. Neighbors or the association enforce them. They are not the same tool as a tax lien."),
        ("Building codes mainly regulate:",
         "How structures are designed and built, for safety",
         ["The commission split between brokers", "Who inherits a life estate", "The interest rate on a mortgage"],
         "Building codes set construction standards. Zoning regulates use and bulk. They work together but they are not the same ordinance."),
        ("Flood-zone rules and inland-wetland rules are examples of:",
         "Government controls on special land types",
         ["Private licenses", "Personal property", "Novation"],
         "The outline groups flood zones and wetlands as regulation of special land. Development there can require extra permits, elevation, or setbacks."),
        ("A buyer plans a daycare in a house zoned single-family only. The licensee should:",
         "Tell the buyer to verify zoning and any needed approvals before relying on that use",
         ["Promise the use is legal because the house has a kitchen", "Ignore use and discuss only paint colors", "Record a new deed that changes the zone"],
         "A licensee does not rezone property by optimism. Proposed use is a reason to check public and private land-use controls before the buyer is locked in."),
        ("Lead, asbestos, underground tanks, and mold are grouped on the outline as:",
         "Environmental hazards that can affect use, value, and disclosure",
         ["Fixtures in every sale", "Forms of joint tenancy", "Government survey monuments"],
         "Environmental hazards can limit use, require abatement, and be material facts. The exam expects you to recognize the hazard, not to design the cleanup."),
        ("A contaminated site with a recorded restriction on future use is an example of:",
         "A land-use control tied to environmental condition",
         ["A fee simple that cannot be limited", "An emblement", "A promissory note"],
         "Agencies can require institutional controls, such as deed notices or use limits, so later owners do not treat a cleaned-up or contained site as unrestricted."),
        ("Police power, in land-use terms, is the power to:",
         "Regulate for health, safety, and general welfare, such as through zoning",
         ["Take land for a highway without paying", "Inherit land when someone dies", "Set the broker's commission by statute in every town"],
         "Zoning and building codes are exercises of police power. Eminent domain requires compensation. Commission rates are not set by the police power."),
        ("A homeowner asks the city to allow a small café in a residential zone because the plan meets special criteria in the ordinance. That approval, if granted, is most like:",
         "A special permit or conditional use",
         ["Escheat", "A quitclaim deed", "A discount point"],
         "Conditional or special-use permits allow a use the ordinance contemplates, if conditions are met. A variance relaxes a dimensional or similar rule because of hardship."),
        ("Private restrictions and zoning both limit a lot. When they differ, the owner must generally follow:",
         "The rule that is stricter",
         ["Only the private rule, because zoning never applies", "Only zoning, because deeds cannot restrict use", "Whichever the listing agent prefers"],
         "Both can apply at once. The owner does not get to pick the looser one. A deed covenant can be tighter than zoning, and zoning can forbid something the deed allows."),
        ("A special assessment for a new sidewalk is typically charged:",
         "To the owners who benefit from that improvement",
         ["As a federal income tax on the licensee", "Only to tenants in a month-to-month lease", "As a transfer tax on every deed in the state"],
         "Special assessments fund local improvements and are allocated to benefited parcels. They are not the same as the conveyance tax on a deed."),
    ]
    for stem, correct, wrongs, explanation in land:
        A(item("landuse", stem, correct, wrongs, explanation, event=(stem.startswith("A buyer plans"))))

    # Valuation
    val = [
        ("An appraiser estimates value for a lender's loan. A salesperson's price opinion for a listing is:",
         "A comparative market analysis, which is not an appraisal",
         ["A certified appraisal if the salesperson is careful", "The definition of market value in every case", "A cost-approach appraisal by default"],
         "A CMA or BPO helps a client pick a price. Calling it an appraisal, or performing appraisal work that requires a license, is unauthorized appraisal practice."),
        ("The sales-comparison approach relies mainly on:",
         "Recent prices of similar properties, adjusted for differences",
         ["The cost to rebuild minus depreciation only", "Net operating income divided by a cap rate only", "The owner's original purchase price"],
         "Buyers and appraisers compare the subject to sold comps and adjust for differences such as size, condition, and location. That is the approach most used for houses."),
        ("A brand-new house with no useful sales nearby is often best supported by:",
         "The cost approach",
         ["A gross-rent multiplier taken from a distant factory", "Escheat", "The income approach using zero rent"],
         "The cost approach estimates land value plus the cost of a new building, minus depreciation. It fits new or special-purpose property when comps are thin."),
        ("Reproduction cost means the cost to:",
         "Build an exact replica, using the same materials and design",
         ["Build a similar utility with modern materials", "Buy the land only", "Pay the commission"],
         "Reproduction copies the original. Replacement builds something with similar usefulness using current methods. The exam uses those words differently."),
        ("An apartment building is valued mainly by:",
         "The income approach",
         ["The color of the lobby only", "A life estate", "Metes and bounds"],
         "Income property is bought for its net income. Value can be estimated by capitalizing net operating income or by using a gross-rent multiplier."),
        ("Net operating income divided by a capitalization rate produces an estimate of:",
         "Value",
         ["The commission in dollars", "Depreciation in years", "The loan-to-value ratio"],
         "The income formula is value = NOI / cap rate. Rearranged, cap rate = NOI / value, and NOI = value × cap rate."),
        ("Which expense is subtracted to reach net operating income?",
         "Ordinary operating expenses such as insurance, taxes, and maintenance",
         ["The mortgage principal payment", "The owner's income-tax bill", "Depreciation taken on the tax return"],
         "NOI is income after operating expenses and before debt service and income taxes. Mortgage payments are not an operating expense in the cap-rate formula."),
        ("A comp sold for $20,000 more because it has a garage the subject lacks. In the sales comparison, the adjustment is:",
         "Subtract $20,000 from the comp's price",
         ["Add $20,000 to the comp's price", "Add $20,000 to the subject's price and ignore the comp", "Make no adjustment"],
         "Adjust the comparable, not the subject. The comp is better, so its price is adjusted downward to match the subject."),
        ("Functional obsolescence is a loss in value from:",
         "Outdated design or features, such as a poor floor plan",
         ["A nearby factory that is outside the property", "Ordinary wear such as a worn roof only", "The land's location next to a park"],
         "Physical deterioration is wear and tear. Functional obsolescence is inside the design. External or economic obsolescence comes from outside the property lines."),
        ("A house next to a newly announced all-night freight yard loses value. That loss is:",
         "External obsolescence",
         ["Physical curable deterioration", "Functional obsolescence from a small closet", "A credit to the seller"],
         "External obsolescence is caused by factors outside the property. It is often incurable by the owner."),
        ("Market value is best described as:",
         "The most probable price a willing buyer and willing seller would agree on, neither under unusual pressure, with typical knowledge",
         ["Whatever the seller originally paid", "The assessed value used for taxes", "The amount of the mortgage"],
         "Market value assumes an arm's-length deal. Assessed value, list price, and loan amount can differ from it."),
        ("The principle that a buyer will not pay more for a property than for an equally desirable substitute is:",
         "Substitution",
         ["Contribution", "Anticipation", "Plottage"],
         "Substitution supports the sales-comparison approach. Contribution asks what one component adds. Anticipation looks at future benefits. Plottage is value created by assembling parcels."),
        ("Combining two small lots into one more valuable parcel illustrates:",
         "Plottage",
         ["Substitution", "Regression", "A lien"],
         "Plottage is the increase from assemblage. The act of joining the lots is assemblage. The value bump is plottage."),
        ("A swimming pool that costs $40,000 to install but adds only $10,000 in market value illustrates:",
         "Contribution",
         ["Escheat", "A trade fixture", "Blockbusting"],
         "Contribution says an improvement is worth what it adds to value, which may be less than its cost."),
        ("Over-improving a house far beyond the neighborhood can run into:",
         "Regression",
         ["Progression, which would pull it up", "A remainder", "Novation"],
         "Regression says a high-end property among modest ones tends to be pulled down. Progression is the opposite: a modest home near better ones can be pulled up."),
        ("An appraisal is required for many federally related loans because:",
         "The lender needs an independent value opinion from a qualified appraiser",
         ["The salesperson's listing price is defined as market value by federal law", "Title insurance sets the price", "The buyer prefers not to know the value"],
         "Federally related transactions generally need an appraisal by a licensed or certified appraiser. A brokerage price opinion does not replace that appraisal. Dollar thresholds change, so the exam point is the role, not a memorized cutoff."),
        ("The first broad steps of an appraisal include defining the problem, gathering data, and then:",
         "Applying the relevant approaches and reconciling them into an opinion",
         ["Setting the commission", "Recording the deed", "Choosing the buyer's lender"],
         "Appraisers define the assignment, collect data, analyze with one or more approaches, and reconcile to a final opinion. They do not negotiate the sale."),
        ("A gross rent multiplier is used by:",
         "Dividing sale price by gross rent",
         ["Dividing net operating income by the cap rate", "Multiplying the tax rate by the assessment", "Subtracting depreciation from land"],
         "GRM = price / gross rent. A value estimate is rent × GRM. It is a rough income tool and does not use the full NOI capitalization formula."),
        ("Assessed value is used mainly to:",
         "Compute property taxes",
         ["Set the salesperson's split", "Replace a title search", "Measure square footage"],
         "Assessors assign assessed value for taxation. It may be a fraction of market value. It is not the appraisal the buyer uses to decide what to offer."),
        ("Highest and best use means the use that is:",
         "Legally allowed, physically possible, financially feasible, and maximally productive",
         ["Whatever the current owner enjoys most", "Always the current use, even if illegal", "The use with the lowest price"],
         "Appraisers test highest and best use with those four filters. A dream use that zoning forbids is not the highest and best use."),
    ]
    for i, (stem, correct, wrongs, explanation) in enumerate(val):
        A(item("valuation", stem, correct, wrongs, explanation, event=(i == 0)))

    return q
